[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "digitai-core"
version = "0.1.0"
description = "DigitAI Core AI Fine-tuning Framework"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml",
    "sentence-transformers",
    "neo4j",
    "tqdm"
]