dataPaths:
  p5Root: "data/p5/p5.xml"
  p5Extracted: "data/p5/p5.json"
  p5GraphLocal: "data/p5/p5Graph.json"         # final graph copy inside your repo

xsltPaths:
  teiExtraction: "digitaiCore/ingestion/teiExtraction.xsl"

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  pass: ""  # You said password is always the same
  p5Cypher: "digitaiCore/graph/p5Cypher.cypher"

modelProfiles:
  qwen2_8b:
    modelPath: "./models/Qwen2-8B"
    tokenizer: "Qwen/Qwen2-8B"
    contextLength: 32768
