dataPaths:
  p5Root: "../data/p5/p5.xml"
  p5Extracted: "../data/p5/p5.json"

xsltPaths:
  teiExtraction: "../digitaiCore/ingestion/teiExtraction.xsl"

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: ""

modelProfiles:
  qwen2_8b:
    modelPath: "./models/Qwen2-8B"
    tokenizer: "Qwen/Qwen2-8B"
    contextLength: 32768
