dataPaths:
  neo4jExport: "data/p5/p5Neo4j.jsonl"            # Output from neo4j_exporter.py (raw node data)
  bgem3Embeddings: "data/p5/p5Embeddings.jsonl"   # Output from embed_bge_m3.py (vector embeddings)
  faissIndex: "data/p5/p5Index.faiss"             # Output from build_faiss_index.py (FAISS binary index)
  faissIdMap: "data/p5/p5IdMap.json"              # Output from build_faiss_index.py (FAISS index ID map)

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "D1g1tAI!"

cypher:
  export_all: "MATCH (n) RETURN elementId(n) AS node_id, n.text AS text, labels(n) AS labels"
  text_only: "MATCH (n) WHERE n.text IS NOT NULL RETURN elementId(n) AS node_id, n.text AS text"

embedding:
  model: "BAAI/bge-m3"
  batch_size: 16
  normalize: true
  throttle: 0.0

performance:
  num_threads: 20
  interop_threads: 4
  tokenizers_parallelism: false

logging:
  enabled: true
  bgem3Log: "logs/bgem3.log"
  faissLog: "logs/faiss.log"
  ragLog: "logs/rag.log"
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"


vectorIndex:
  name: "embedding-index"
  property: "embedding"
  dimension: 1024

llm:
  provider: "ollama"
  model: "qwen:7b"